name: Confirmat-laravel

services:
  laravel:
    image: shinsenter/laravel:latest
    ports: ["180:80", "1443:443", "1443:443/udp"]
    volumes: [../laravel:/var/www/html]
  # httpd:
  #   image: "httpd:2.4.66-alpine"
  #   ports: ["180:80"]
  #   volumes: [../laravel:/var/www/laravel]
  # php:
  #   build:
  #     context: dockerfiles
  #     dockerfile: php.Dockerfile
  #   volumes: [../laravel:/var/www/laravel]
  # mysql:
  #   image: mysql:latest
  #   ports: ["13306:3306"]
  #   env_file: env/mysql.env
  maria:
    image: mariadb:latest
    ports: ["13306:3306"]
    env_file: env/mariadb.env
    volumes: [/database:/var/lib/mysql]
  phpmyadmin:
    image: phpmyadmin:latest
    ports: ["18080:8080"]
  # composer:
  #   build:
  #     context: dockerfiles
  #     dockerfile: composer.Dockerfile
  #   volumes: [../laravel:/var/www/laravel]
